### ISSUE TITLE
Weapons and Cash don't glow like on console.

### ISSUE THREAD

**Issue by xSoaa** [kobraworksmodding/SR2IssuesList#14]
Tervel 360 Screenshots attached.

![image](https://github.com/user-attachments/assets/618dcbd9-ab10-4520-9747-fb284360eda5)

![image](https://github.com/user-attachments/assets/25b5f3f9-ea2d-4bce-9b38-8bfeb029ee79)

**Comment by Tervel1337** [comment]
The issue stems from disabling HDR - the glow is directly tied to it and they never accounted for this so, as such, it works fine with it enabled.
